from dataclasses import dataclass
from typing import Any

from pybird.models.convert import from_float, to_float

@dataclass
class BodyModel:
    h8: float = None
    h9: float = None
    h10: float = None
    h11: float = None
    h12: float = None
    h13: float = None
    h14: float = None
    h15: float = None
    h16: float = None
    delta11: float = None
    delta12: float = None
    delta13: float = None
    delta14: float = None
    delta15: float = None
    delta16: float = None
    delta17: float = None
    delta18: float = None
    delta19: float = None
    delta20: float = None
    delta21: float = None
    delta22: float = None
    delta23: float = None
    delta24: float = None
    delta25: float = None
    delta26: float = None
    delta27: float = None
    delta28: float = None
    delta29: float = None
    delta30: float = None
    delta31: float = None
    delta32: float = None
    delta33: float = None
    delta34: float = None
    delta35: float = None
    delta36: float = None
    delta37: float = None
    delta38: float = None
    delta39: float = None
    delta40: float = None
    delta41: float = None
    delta42: float = None
    delta43: float = None
    delta44: float = None
    delta45: float = None
    delta46: float = None
    delta47: float = None
    delta48: float = None
    delta49: float = None
    delta50: float = None
    delta51: float = None
    delta52: float = None
    delta53: float = None
    delta54: float = None
    delta55: float = None
    delta56: float = None
    delta57: float = None
    delta58: float = None
    delta59: float = None
    delta60: float = None
    delta61: float = None
    delta62: float = None
    delta63: float = None
    delta64: float = None

    @staticmethod
    def from_dict(obj: Any) -> 'BodyModel':
        assert isinstance(obj, dict)
        h8 = from_float(obj.get("h8"))
        h9 = from_float(obj.get("h9"))
        h10 = from_float(obj.get("h10"))
        h11 = from_float(obj.get("h11"))
        h12 = from_float(obj.get("h12"))
        h13 = from_float(obj.get("h13"))
        h14 = from_float(obj.get("h14"))
        h15 = from_float(obj.get("h15"))
        h16 = from_float(obj.get("h16"))
        delta11 = from_float(obj.get("delta11"))
        delta12 = from_float(obj.get("delta12"))
        delta13 = from_float(obj.get("delta13"))
        delta14 = from_float(obj.get("delta14"))
        delta15 = from_float(obj.get("delta15"))
        delta16 = from_float(obj.get("delta16"))
        delta17 = from_float(obj.get("delta17"))
        delta18 = from_float(obj.get("delta18"))
        delta19 = from_float(obj.get("delta19"))
        delta20 = from_float(obj.get("delta20"))
        delta21 = from_float(obj.get("delta21"))
        delta22 = from_float(obj.get("delta22"))
        delta23 = from_float(obj.get("delta23"))
        delta24 = from_float(obj.get("delta24"))
        delta25 = from_float(obj.get("delta25"))
        delta26 = from_float(obj.get("delta26"))
        delta27 = from_float(obj.get("delta27"))
        delta28 = from_float(obj.get("delta28"))
        delta29 = from_float(obj.get("delta29"))
        delta30 = from_float(obj.get("delta30"))
        delta31 = from_float(obj.get("delta31"))
        delta32 = from_float(obj.get("delta32"))
        delta33 = from_float(obj.get("delta33"))
        delta34 = from_float(obj.get("delta34"))
        delta35 = from_float(obj.get("delta35"))
        delta36 = from_float(obj.get("delta36"))
        delta37 = from_float(obj.get("delta37"))
        delta38 = from_float(obj.get("delta38"))
        delta39 = from_float(obj.get("delta39"))
        delta40 = from_float(obj.get("delta40"))
        delta41 = from_float(obj.get("delta41"))
        delta42 = from_float(obj.get("delta42"))
        delta43 = from_float(obj.get("delta43"))
        delta44 = from_float(obj.get("delta44"))
        delta45 = from_float(obj.get("delta45"))
        delta46 = from_float(obj.get("delta46"))
        delta47 = from_float(obj.get("delta47"))
        delta48 = from_float(obj.get("delta48"))
        delta49 = from_float(obj.get("delta49"))
        delta50 = from_float(obj.get("delta50"))
        delta51 = from_float(obj.get("delta51"))
        delta52 = from_float(obj.get("delta52"))
        delta53 = from_float(obj.get("delta53"))
        delta54 = from_float(obj.get("delta54"))
        delta55 = from_float(obj.get("delta55"))
        delta56 = from_float(obj.get("delta56"))
        delta57 = from_float(obj.get("delta57"))
        delta58 = from_float(obj.get("delta58"))
        delta59 = from_float(obj.get("delta59"))
        delta60 = from_float(obj.get("delta60"))
        delta61 = from_float(obj.get("delta61"))
        delta62 = from_float(obj.get("delta62"))
        delta63 = from_float(obj.get("delta63"))
        delta64 = from_float(obj.get("delta64"))
        return BodyModel(h8, h9, h10, h11, h12, h13, h14, h15, h16, delta11, delta12, delta13, delta14, delta15, delta16, delta17, delta18, delta19, delta20, delta21, delta22, delta23, delta24, delta25, delta26, delta27, delta28, delta29, delta30, delta31, delta32, delta33, delta34, delta35, delta36, delta37, delta38, delta39, delta40, delta41, delta42, delta43, delta44, delta45, delta46, delta47, delta48, delta49, delta50, delta51, delta52, delta53, delta54, delta55, delta56, delta57, delta58, delta59, delta60, delta61, delta62, delta63, delta64)

    def to_dict(self) -> dict:
        result: dict = {}
        result["h8"] = to_float(self.h8)
        result["h9"] = to_float(self.h9)
        result["h10"] = to_float(self.h10)
        result["h11"] = to_float(self.h11)
        result["h12"] = to_float(self.h12)
        result["h13"] = to_float(self.h13)
        result["h14"] = to_float(self.h14)
        result["h15"] = to_float(self.h15)
        result["h16"] = to_float(self.h16)
        result["delta11"] = to_float(self.delta11)
        result["delta12"] = to_float(self.delta12)
        result["delta13"] = to_float(self.delta13)
        result["delta14"] = to_float(self.delta14)
        result["delta15"] = to_float(self.delta15)
        result["delta16"] = to_float(self.delta16)
        result["delta17"] = to_float(self.delta17)
        result["delta18"] = to_float(self.delta18)
        result["delta19"] = to_float(self.delta19)
        result["delta20"] = to_float(self.delta20)
        result["delta21"] = to_float(self.delta21)
        result["delta22"] = to_float(self.delta22)
        result["delta23"] = to_float(self.delta23)
        result["delta24"] = to_float(self.delta24)
        result["delta25"] = to_float(self.delta25)
        result["delta26"] = to_float(self.delta26)
        result["delta27"] = to_float(self.delta27)
        result["delta28"] = to_float(self.delta28)
        result["delta29"] = to_float(self.delta29)
        result["delta30"] = to_float(self.delta30)
        result["delta31"] = to_float(self.delta31)
        result["delta32"] = to_float(self.delta32)
        result["delta33"] = to_float(self.delta33)
        result["delta34"] = to_float(self.delta34)
        result["delta35"] = to_float(self.delta35)
        result["delta36"] = to_float(self.delta36)
        result["delta37"] = to_float(self.delta37)
        result["delta38"] = to_float(self.delta38)
        result["delta39"] = to_float(self.delta39)
        result["delta40"] = to_float(self.delta40)
        result["delta41"] = to_float(self.delta41)
        result["delta42"] = to_float(self.delta42)
        result["delta43"] = to_float(self.delta43)
        result["delta44"] = to_float(self.delta44)
        result["delta45"] = to_float(self.delta45)
        result["delta46"] = to_float(self.delta46)
        result["delta47"] = to_float(self.delta47)
        result["delta48"] = to_float(self.delta48)
        result["delta49"] = to_float(self.delta49)
        result["delta50"] = to_float(self.delta50)
        result["delta51"] = to_float(self.delta51)
        result["delta52"] = to_float(self.delta52)
        result["delta53"] = to_float(self.delta53)
        result["delta54"] = to_float(self.delta54)
        result["delta55"] = to_float(self.delta55)
        result["delta56"] = to_float(self.delta56)
        result["delta57"] = to_float(self.delta57)
        result["delta58"] = to_float(self.delta58)
        result["delta59"] = to_float(self.delta59)
        result["delta60"] = to_float(self.delta60)
        result["delta61"] = to_float(self.delta61)
        result["delta62"] = to_float(self.delta62)
        result["delta63"] = to_float(self.delta63)
        result["delta64"] = to_float(self.delta64)
        return result